runtime: nodejs14
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
env_variables:
  SHOWROOM_BASE_URL: "https://showroom-kedarify.netlify.app"
  DEBUG_MODE: "https://showroom-kedarify.netlify.app"