version: "3.3"

services:
  api:
    build: .
    image: kedarify-api
    container_name: kedarify-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app-network
    links:
      - "db:database"
    env_file: api.local.env
    depends_on:
      - db

  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
